version: '3.8'

services:
  emqx:
    image: emqx/emqx:5.0.26
    container_name: emqx_conchat_prod
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    environment:
      - "EMQX_ALLOW_ANONYMOUS=false" 
    volumes:
      - emqx_data_prod:/opt/emqx/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: conchat_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    
    restart: always
    depends_on:
      - emqx

volumes:
  emqx_data_prod: