version: '3.8'

services:

  emqx:
    image: emqx/emqx:5.0.26
    container_name: emqx_conchat
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    environment:
      - "EMQX_ALLOW_ANONYMOUS=true"
    volumes:
      - emqx_data:/opt/emqx/data

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conchat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API RESTful
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: conchat_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql://user:password@db:5432/conchat_db
      
    volumes:
      - ./backend:/app

    restart: unless-stopped
    depends_on:
      - emqx
      - db

volumes:
  emqx_data:
  postgres_data: